server:
  port: 8888
spring:
  application:
    name: redis-stream
  redis:
    host: 47.100.91.189
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        enabled: true
        max-active: 20  # ????????????????????
        max-wait: 0   # ???????????????????????
        max-idle: 5   # ???????????
        min-idle: 1    # ???????????
    timeout: 30000 #??

